[build]
  # Indique le dossier où se trouve le package.json (la base de votre projet)
  base = "linkoova---next-gen-agency"
  # Dit à Netlify d'exécuter la commande "npm run build"
  command = "npm run build"
  # Indique que le dossier compilé se trouve DANS le dossier de base (simplement "dist")
  publish = "dist"
